server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider #nacos 注册服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'